# Exported from Render on 2024-04-02T19:09:42Z
services:
- type: web
  name: caddy
  runtime: docker
  healthCheckPath: /caddyhealth
  envVars:
  - key: DOWNSTREAM_HOST
    sync: false
  - key: DOWNSTREAM_PORT
    sync: false
  region: oregon
version: "1"
